import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shivam Ingle
 */
public class AllEmployeeWorking extends javax.swing.JFrame {
 
    /**
     * Creates new form AllEmployeeWorking
     */
    public AllEmployeeWorking() {
        initComponents();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from employee where status='Working'");
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(2),rs.getString(1),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});
            }
                
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(480, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close all jframe.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 13, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Xls.png"))); // NOI18N
        jButton2.setText("Export");
        jButton2.setMaximumSize(new java.awt.Dimension(63, 39));
        jButton2.setMinimumSize(new java.awt.Dimension(63, 39));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 110, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Mobile Number", "Father Name", "Mother Name", "Email", "Address", "Aadhar Number", "Designation"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 65, 676, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pages background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 710, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jf =new JFileChooser();
        jf.setPreferredSize(new Dimension(600, 600));
        jf.showSaveDialog(this);
        File sf =jf.getSelectedFile();
        if(sf != null){
            sf=new File(sf.toString()+".xlsx");
            try
            {
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                ResultSet rs = st.executeQuery("select * from employee where status='Working' ");
                XSSFWorkbook wb = new XSSFWorkbook();
                XSSFSheet spreadSheet = wb.createSheet("TrySheet");
                XSSFRow row = spreadSheet.createRow(1);
                XSSFCell cell;
                cell=row.createCell(1);
                cell.setCellValue("Mobile Number");
                cell=row.createCell(2);
                cell.setCellValue("Name");
                cell=row.createCell(3);
                cell.setCellValue("Father Name");
                cell=row.createCell(4);
                cell.setCellValue("Mother Name");
                cell=row.createCell(5);
                cell.setCellValue("Email");
                cell=row.createCell(6);
                cell.setCellValue("Address");
                cell=row.createCell(7);
                cell.setCellValue("Aadhaar");
                cell=row.createCell(8);
                cell.setCellValue("Designation");
               
                int i = 2;
                while (rs.next()) {
                    row = spreadSheet.createRow(i);
                    cell=row.createCell(1);
                    cell.setCellValue(rs.getString("mobileNo"));
                    cell=row.createCell(2);
                    cell.setCellValue(rs.getString("name"));
                    cell=row.createCell(3);
                    cell.setCellValue(rs.getString("father"));
                    cell=row.createCell(4);
                    cell.setCellValue(rs.getString("mother"));
                    cell=row.createCell(5);
                    cell.setCellValue(rs.getString("email"));
                    cell=row.createCell(6);
                    cell.setCellValue(rs.getString("address"));
                    cell=row.createCell(7);
                    cell.setCellValue(rs.getString("aadhaar"));
                    cell=row.createCell(8);
                    cell.setCellValue(rs.getString("designation"));
                   
                    i++;
                }
                FileOutputStream output = new FileOutputStream(sf);
                wb.write(output);
                output.close();
                JOptionPane.showMessageDialog(null, "Xlxss created");
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "error");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllEmployeeWorking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllEmployeeWorking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllEmployeeWorking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllEmployeeWorking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllEmployeeWorking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
