import java.sql.*;
import Project.ConnectionProvider;
import java.awt.Dimension;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author radhi
 */
public class AllStudentLiving extends javax.swing.JFrame {

    /**
     * Creates new form AllStudentLiving
     */
    public AllStudentLiving() {
        initComponents();
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);

    try {
        Connection con = ConnectionProvider.getCon();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select * from student where status='living'");
        
        while (rs.next()) {
            // Debug print to console
            System.out.println("Loaded student: " + rs.getString("name"));
            
            model.addRow(new Object[] {
                rs.getString("name"),
                rs.getString("mobileNo"),
                rs.getString("fatherName"),
                rs.getString("motherName"),
                rs.getString("email"),
                rs.getString("address"),
                rs.getString("collegeName"),
                rs.getString("aadhar"),
                rs.getString("roomNo")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(480, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close all jframe.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 13, 94, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Xls.png"))); // NOI18N
        jButton2.setText("Export");
        jButton2.setMaximumSize(new java.awt.Dimension(63, 39));
        jButton2.setMinimumSize(new java.awt.Dimension(63, 39));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 110, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Mobile Number", "Father Name", "Mother Name", "Email", "Address", "Collage Name", "Aadhar Number", "Room Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 670, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pages background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 690, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jf =new JFileChooser();
        jf.setPreferredSize(new Dimension(600, 600));
        jf.showSaveDialog(this);
        File sf =jf.getSelectedFile();
        if(sf != null){
       sf=new File(sf.toString()+".xlsx");
         try
        {
             Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
        ResultSet rs = st.executeQuery("select * from student where status='living'");
        XSSFWorkbook wb = new XSSFWorkbook();
        XSSFSheet spreadSheet = wb.createSheet("TrySheet");
        XSSFRow row = spreadSheet.createRow(1);
        XSSFCell cell;
        cell=row.createCell(1);
        cell.setCellValue("Mobile Number");
        cell=row.createCell(2);
        cell.setCellValue("Name");
        cell=row.createCell(3);
        cell.setCellValue("Father Name");
        cell=row.createCell(4);
        cell.setCellValue("Mother Name");
        cell=row.createCell(5);
        cell.setCellValue("Email");
        cell=row.createCell(6);
        cell.setCellValue("Address");
        cell=row.createCell(7);
        cell.setCellValue("College");
        cell=row.createCell(8);
        cell.setCellValue("Aadhaar");
        cell=row.createCell(9);
        cell.setCellValue("Room No");
        int i = 2;
        while (rs.next()) {
                      row = spreadSheet.createRow(i);
                      cell=row.createCell(1);
                      cell.setCellValue(rs.getString("mobileNo"));
                       cell=row.createCell(2);
                      cell.setCellValue(rs.getString("name"));
                      cell=row.createCell(3);
                      cell.setCellValue(rs.getString("father"));
                      cell=row.createCell(4);
                      cell.setCellValue(rs.getString("mother"));
                      cell=row.createCell(5);
                      cell.setCellValue(rs.getString("email"));
                      cell=row.createCell(6);
                      cell.setCellValue(rs.getString("address"));
                      cell=row.createCell(7);
                      cell.setCellValue(rs.getString("college"));
                      cell=row.createCell(8);
                      cell.setCellValue(rs.getString("aadhaar"));
                      cell=row.createCell(9);
                      cell.setCellValue(rs.getString("roomNo"));
                      i++;
        }
        FileOutputStream output = new FileOutputStream(sf);
        wb.write(output);
        output.close();
        JOptionPane.showMessageDialog(null, "Xlxss created");
         
    }
    catch(Exception e)
     {
         System.out.println(e);
     }
        }
        else{
            JOptionPane.showMessageDialog(null, "error");
         System.out.println("error");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllStudentLiving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllStudentLiving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllStudentLiving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllStudentLiving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllStudentLiving().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
